<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SRN Information</title>
</head>
<body>
   
    <p>
        Hi, A new service request has been generated by client. The details of the request are mentioned below:
    </p>

    <p><strong>Brand:</strong> {{ ucfirst($ticket->brand) }}</p>
    <p><strong>Title:</strong> {{ ucfirst($ticket->title) }}</p>
    <p><strong>Category:</strong> {{ ucfirst($ticket->category_name) }}</p>
    <p><strong>Summary:</strong> {{ $ticket->summary }}</p>
    <p><strong>Priority:</strong> {{ ucfirst($ticket->priority) }}</p>
</body>
</html>